[workspace]
resolver = "2" # Important! wgpu/Bevy needs this!
members = [
    "ronky",
    "ronky-components",
    "ronky-demo",
    "ronky-window",
    "view/ronky-view",
    "view/ronky-view-label"
]
